#Unit-3 Data Wrangling
##Experiment 12  To perform pre-processing on a dataset and dealing with missing values

###ROHAN KUMBHAR
###PRN-25070123141
####ENTC A2

In [ ]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1':[11,21,np.nan],'C2':[15,np.nan,np.nan],'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
df1.isna() #Boolean function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df1.isna().sum() #coloumn wise na values

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
df1.dropna() #NaN Row are dropped

     C1    C2  C3
0  11.0  15.0  10

In [ ]:
df1.fillna(value='DEFAULT')

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [ ]:
df1.fillna(df1.mean())  #Mean values of colouumn are calculated

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [ ]:
#Dataset-1
import pandas as pd
data= { "Roll No":[101,102,103,104,105],
       "Name":["Ayush","Aaryan","Aditya","Harsh","Anish"],
        "Age":[20,"-",21,20,"22"],
        "Marks":[85,90,"-",88,76],
        "Department":["CSE","IT","CSE","CSE","E&TC",],
        "Admission_Date":["01-06-2023","02-06-2023","04-06-2023","06-06-2023","08/06/2023"]
        }
df=pd.DataFrame(data)

#Save as CSV
df.to_csv("student_data.csv",index=False)

In [ ]:
#Step 2. Replace '-' with NaN to mark missing values

df.replace("-",np.nan,inplace=True)

#Convert colmns to numeric where needed

df["Age"]=pd.to_numeric(df["Age"],errors='coerce')
df["Marks"]=pd.to_numeric(df["Marks"],errors='coerce')
df

### When converting data(Like strings--> datetime),
### if some valuues are invalid or cannot be converted,
### instead of thowing an error, it wll:
### ➡️Replace those invalid values wi NaT (Not a Time)'''

/tmp/ipykernel_619/3376336122.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-",np.nan,inplace=True)

   Roll No    Name   Age  Marks Department Admission_Date
0      101   Ayush  20.0   85.0        CSE     01-06-2023
1      102  Aaryan   NaN   90.0         IT     02-06-2023
2      103  Aditya  21.0    NaN        CSE     04-06-2023
3      104   Harsh  20.0   88.0        CSE     06-06-2023
4      105   Anish  22.0   76.0       E&TC     08/06/2023

In [ ]:
# Step 3. Check for missing values

print("\nMissing VaLues: ")
print(df.isnull().sum())

Missing VaLues:
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [ ]:
#Fill missing age with mean

df["Age"].fillna(df["Age"].mean(),inplace=True)
df

/tmp/ipykernel_619/3338185231.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

   Roll No    Name    Age  Marks Department Admission_Date
0      101   Ayush  20.00   85.0        CSE     01-06-2023
1      102  Aaryan  20.75   90.0         IT     02-06-2023
2      103  Aditya  21.00    NaN        CSE     04-06-2023
3      104   Harsh  20.00   88.0        CSE     06-06-2023
4      105   Anish  22.00   76.0       E&TC     08/06/2023

In [ ]:
#Fill missing marks with median
df["Marks"].fillna(df["Marks"].median(), inplace = True)
df

/tmp/ipykernel_619/3133186580.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(), inplace = True)

   Roll No    Name    Age  Marks Department Admission_Date
0      101   Ayush  20.00   85.0        CSE     01-06-2023
1      102  Aaryan  20.75   90.0         IT     02-06-2023
2      103  Aditya  21.00   86.5        CSE     04-06-2023
3      104   Harsh  20.00   88.0        CSE     06-06-2023
4      105   Anish  22.00   76.0       E&TC     08/06/2023

In [ ]:
print(df.isnull().sum())

Roll No           0
Name              0
Age               0
Marks             0
Department        0
Admission_Date    0
dtype: int64

In [ ]:
#Fix inconsistent text formatting
df["Department"] = df["Department"].str.upper()
df

   Roll No    Name    Age  Marks Department Admission_Date
0      101   Ayush  20.00   85.0        CSE     01-06-2023
1      102  Aaryan  20.75   90.0         IT     02-06-2023
2      103  Aditya  21.00   86.5        CSE     04-06-2023
3      104   Harsh  20.00   88.0        CSE     06-06-2023
4      105   Anish  22.00   76.0       E&TC     08/06/2023

In [ ]:
#Step 6 - Convert Admission_Date to standard datetime format

df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], errors='coerce')
df

   Roll No    Name    Age  Marks Department Admission_Date
0      101   Ayush  20.00   85.0        CSE     2023-01-06
1      102  Aaryan  20.75   90.0         IT     2023-02-06
2      103  Aditya  21.00   86.5        CSE     2023-04-06
3      104   Harsh  20.00   88.0        CSE     2023-06-06
4      105   Anish  22.00   76.0       E&TC            NaT

In [ ]:
#Step 8: Save cleaned dataset

df.to_csv("cleaned_student_data.csv", index=False)

print("\nCleaned CSV file saved as cleaned_student_data.csv")
df

Cleaned CSV file saved as cleaned_student_data.csv

   Roll No    Name    Age  Marks Department Admission_Date
0      101   Ayush  20.00   85.0        CSE     2023-01-06
1      102  Aaryan  20.75   90.0         IT     2023-02-06
2      103  Aditya  21.00   86.5        CSE     2023-04-06
3      104   Harsh  20.00   88.0        CSE     2023-06-06
4      105   Anish  22.00   76.0       E&TC            NaT

In [ ]:
#Working with missing values on Dataset-2
#Upload the Dataset

import pandas as pd
import numpy as np
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.isna().sum()  #Attributes are displayed

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
#Imputing the missing value
#1.Luggage Room
df['Luggage.room']=df['Luggage.room'].fillna(value=df['Luggage.room'].mean())

In [ ]:
#2. Rear seat room
df['Rear.seat.room']=df['Rear.seat.room'].fillna(value=df['Rear.seat.room'].mean())
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [ ]:
df['AirBags'] = df['AirBags'].fillna(value=df['AirBags'].mode().values[0])
df.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [ ]:
#Save Cleaned dataset
df.to_csv("cleaned_Cars93.csv",index=False)
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver only,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,Driver only,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,Driver only,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000